name: Docker Image CI

on:
  push:
    branches:
      - test-new-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t orenleung/jax_tpu:${{GITHUB_REF_NAME}} .
    
    - uses: docker/login-action@v1
    - name: Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}